const blessed = require("blessed");
const contrib = require("blessed-contrib");
const chalk = require("chalk");
const colors = require("colors/safe");
var screen = blessed.screen();
//create layout and widgets
// var grid = new contrib.grid({ rows: 12, cols: 12, screen: screen });

var table = contrib.table({
  keys: true,
  fg: "white",
  selectedFg: "white",
  selectedBg: "blue",
  interactive: false,
  label: "Monopoly Board",
  border: { type: "line", fg: "cyan" },
  columnSpacing: 0,
  columnWidth: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
});

table.focus();
screen.append(table);

table.setData({
  headers: [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
  data: [
    [
      colors.bgWhite.black("FREE"),
      colors.bgRed.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("LUCK"),
      colors.bgRed.black("⌂⌂⌂⌂"),
      colors.bgRed.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("CHOO"),
      colors.bgBrightYellow.black("⌂⌂⌂⌂"),
      colors.bgBrightYellow.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("UTIL"),
      colors.bgBrightYellow.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("GOTO"),
    ],
    [
      colors.bgWhite.black("PARK"),
      colors.bgRed.black("    "),
      colors.bgWhite.black("    "),
      colors.bgRed.black("    "),
      colors.bgRed.black("    "),
      colors.bgWhite.black("CHOO"),
      colors.bgBrightYellow.black("    "),
      colors.bgBrightYellow.black("    "),
      colors.bgWhite.black("    "),
      colors.bgBrightYellow.black("    "),
      colors.bgWhite.black("JAIL"),
    ],
    // ROW 2
    [
      colors.bgYellow.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("⌂⌂⌂⌂"),
    ],
    [
      colors.bgYellow.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("    "),
    ],
    // ROW 3
    [
      colors.bgYellow.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("⌂⌂⌂⌂"),
    ],
    [
      colors.bgYellow.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("    "),
    ],
    // ROW 4
    [
      colors.bgWhite.black("COMM"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black("COMM"),
    ],
    [
      colors.bgWhite.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black("    "),
    ],
    // ROW 5
    [
      colors.bgYellow.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("⌂⌂⌂⌂"),
    ],
    [
      colors.bgYellow.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgGreen.black("    "),
    ],
    // ROW 6
    [
      colors.bgWhite.black("CHOO"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black("CHOO"),
    ],
    [
      colors.bgWhite.black("CHOO"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black("CHOO"),
    ],
    // ROW 7
    [
      colors.bgBrightMagenta.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBrightWhite.black("LUCK"),
    ],
    [
      colors.bgBrightMagenta.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBrightWhite.black("    "),
    ],
    // ROW 8
    [
      colors.bgBrightMagenta.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBlue.black("⌂⌂⌂⌂"),
    ],
    [
      colors.bgBrightMagenta.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBlue.black("    "),
    ],
    // ROW 9
    [
      colors.bgWhite.black("UTIL"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black("WLTH"),
    ],
    [
      colors.bgWhite.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgWhite.black(" TAX"),
    ],
    // ROW 10
    [
      colors.bgBrightMagenta.black("⌂⌂⌂⌂"),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBlue.black("⌂⌂⌂⌂"),
    ],
    [
      colors.bgBrightMagenta.black("    "),
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      "    ",
      colors.bgBlue.black("    "),
    ],
    [
      colors.bgWhite.black("JAIL"),
      colors.bgCyan.black("⌂⌂⌂⌂"),
      colors.bgCyan.black("⌂⌂⌂⌂"),
      colors.bgBrightWhite.black("LUCK"),
      colors.bgCyan.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("CHOO"),
      colors.bgWhite.black("LXRY"),
      colors.bgMagenta.black("⌂⌂⌂⌂"),
      colors.bgWhite.black("UTIL"),
      colors.bgMagenta.black("⌂⌂⌂⌂"),
      colors.bgWhite.black(" GO "),
    ],
    [
      colors.bgWhite.black("JAIL"),
      colors.bgCyan.black("    "),
      colors.bgCyan.black("    "),
      colors.bgBrightWhite.black("    "),
      colors.bgCyan.black("    "),
      colors.bgWhite.black("CHOO"),
      colors.bgWhite.black(" TAX"),
      colors.bgMagenta.black("    "),
      colors.bgWhite.black("    "),
      colors.bgMagenta.black("    "),
      colors.bgWhite.black(" GO "),
    ],
  ],
});

screen.key(["escape", "q", "C-c"], function (ch, key) {
  return process.exit(0);
});

screen.render();

screen.key(["escape", "q", "C-c"], function (ch, key) {
  return process.exit(0);
});

screen.render();
